### ISSUE TITLE
Implement UI for learning CLI instructions

### ISSUE THREAD

**Issue by AlexJupiter** [yldio/joyent-portal#1356] opened 2018-04-03 09:47 UTC
Implementing these designs:
https://www.figma.com/file/GWTYkBRQT9QPQyjEmHd0MnZi/CI-CLI-Instructions?node-id=12%3A1026

The creation of the CLI instructions will be handled in a separate ticket: https://github.com/yldio/joyent-portal/issues/1355

**Comment by yaili** [comment] 2018-05-03 14:00
Duplicate of #1298

**Closed by yaili** 2018-05-03 14:00 UTC
Labels: engineering, medium priority
