### ISSUE TITLE
Instance List

### ISSUE THREAD

**Issue by AlexJupiter** [yldio/joyent-portal#805] opened 2017-10-20 09:55 UTC
A user must be able to view all instances they have deployed in a data center to allow them to judge the overall performance of their instance and make quick actions.

KPIs:
1. A user must be able to judge very high level information on their instance (such as name and status)
2. A user must be able to perform quick actions on instances (such as stop and restart), singularly, and in bulk
3. A user should be able to find a specific instance from a large number

**Comment by yaili** [comment] 2017-10-24 10:28
Closing as it's duplicate of #783 - confidence label moved to original epic.

**Closed by yaili** 2017-10-24 10:28 UTC
Labels: epic, low confidence
