### ISSUE TITLE
Bugs from Anthony user testing session

### ISSUE THREAD

**Issue by hollowtf** [yldio/joyent-portal#1259] opened 2018-02-26 13:37 UTC
- [x] "Loading" animation should read "Deleting" when deleting instance/snapshot
- [x] ‘Updated’ columnn in Snapshot table implies that Snapshots can be updated, which is incorrect and should be removed

**Comment by ramitos** [comment] 2018-02-26 16:03
removed 

> - [ ] When a user collapses the user script card in Create Instance flow, it currently shows the entire script on one line in the card playback. Instead, can we jst show the first line of code in the playback.

because it's a duplicate of #1187. Also, I added a comment there https://github.com/yldio/joyent-portal/issues/1187#issuecomment-368107806

**Closed** 2018-02-26 18:45 UTC
Labels: bug, engineering
